// This generated file is imported by "turnline.dart" residing in the same directory as this file
// and should not be imported or exported by any other file.
//
//   Source File  : Lark/Katikati-Core/katikati_lib/lib/datatypes/nook_turnline.dart
//   Source SHA   : 80b46f4579a63e29f68669e94cf5ceaf957ee0e4bcfcbbf2c5100d5da0cdae72
//   Generated by : danrubel
//
// Use "kktool codegen Lark/Katikati-Core/katikati_lib/lib/datatypes/nook_turnline.dart" to regenerate this file.
// Adjust the imports as necessary as they are preserved when the code is regenerated.

import 'dart:async';

import 'package:katikati_ui_lib/components/datatypes/doc_storage_util.dart';
import 'package:katikati_ui_lib/components/logger.dart';

class Turnline {
  String title;
  List<TurnlineStep> steps;

  static Turnline fromSnapshot(DocSnapshot doc, [Turnline modelObj]) => fromData(doc.data, modelObj)..docId = doc.id;

  static Turnline fromData(data, [Turnline modelObj]) {
    if (data == null) return null;
    return (modelObj ?? Turnline())
      ..title = data['title']?.toString()
      ..steps = List_fromData<TurnlineStep>(_log, 'steps', data);
  }

  static StreamSubscription listen(DocStorage docStorage, TurnlineCollectionListener listener,
          {String collectionRoot, OnErrorListener onError, @Deprecated('use onError instead') OnErrorListener onErrorListener}) =>
      listenForUpdates<Turnline>(_log, docStorage, listener, collectionRoot, Turnline.fromSnapshot, onError: onError ?? onErrorListener);

  Map<String, dynamic> toData() {
    return {
      if (title != null) 'title': title,
      if (steps != null) 'steps': steps,
    };
  }

  @override
  String toString() => 'Turnline [$docId]: ${toData().toString()}';
}

typedef TurnlineCollectionListener = void Function(
  List<Turnline> added,
  List<Turnline> modified,
  List<Turnline> removed,
);

class TurnlineStep {
  String title;
  String description;
  List<String> tagIds;
  List<String> standardMessagesIds;
  bool done;
  bool verified;
  Map<String, dynamic> additionalInfo;

  static TurnlineStep fromSnapshot(DocSnapshot doc, [TurnlineStep modelObj]) => fromData(doc.data, modelObj)..docId = doc.id;

  static TurnlineStep fromData(data, [TurnlineStep modelObj]) {
    if (data == null) return null;
    return (modelObj ?? TurnlineStep())
      ..title = data['title']?.toString()
      ..description = data['description']?.toString()
      ..tagIds = List_fromData<String>(_log, 'tagIds', data)
      ..standardMessagesIds = List_fromData<String>(_log, 'standardMessagesIds', data)
      ..done = bool_fromData(_log, 'done', data)
      ..verified = bool_fromData(_log, 'verified', data)
      ..additionalInfo = Map_fromData<dynamic>(_log, 'additionalInfo', data);
  }

  static StreamSubscription listen(DocStorage docStorage, TurnlineStepCollectionListener listener,
          {String collectionRoot, OnErrorListener onError, @Deprecated('use onError instead') OnErrorListener onErrorListener}) =>
      listenForUpdates<TurnlineStep>(_log, docStorage, listener, collectionRoot, TurnlineStep.fromSnapshot, onError: onError ?? onErrorListener);

  Map<String, dynamic> toData() {
    return {
      if (title != null) 'title': title,
      if (description != null) 'description': description,
      if (tagIds != null) 'tagIds': tagIds,
      if (standardMessagesIds != null) 'standardMessagesIds': standardMessagesIds,
      if (done != null) 'done': done,
      if (verified != null) 'verified': verified,
      if (additionalInfo != null) 'additionalInfo': additionalInfo,
    };
  }

  @override
  String toString() => 'TurnlineStep [$docId]: ${toData().toString()}';
}

typedef TurnlineStepCollectionListener = void Function(
  List<TurnlineStep> added,
  List<TurnlineStep> modified,
  List<TurnlineStep> removed,
);

final _log = Logger('turnline.g.dart');
