// This generated file is imported by "project.dart" residing in the same directory as this file
// and should not be imported or exported by any other file.
//
//   Source File  : Lark/Katikati-Core/katikati_lib/lib/datatypes/nook_project.dart
//   Source SHA   : 6731471cc452414d66047f24295f7cd910ad96e2e123d1e5de31ceaeae6949dc
//   Generated by : mariana
//
// Use "kktool codegen Lark/Katikati-Core/katikati_lib/lib/datatypes/nook_project.dart" to regenerate this file.
// Adjust the imports as necessary as they are preserved when the code is regenerated.

import 'dart:async';

import 'package:katikati_ui_lib/datatypes/doc_storage_util.dart';
import 'package:katikati_ui_lib/components/logger.dart';

class Project {
  static const collectionName = 'projects';

  String docId;
  String projectName;
  String allowedEmailDomainsRegex;
  Map<String, String> allowedEmailDomainsMap;
  String firstLanguage;
  String secondLanguage;
  int messageCharacterLimit;

  String get projectId => docId;

  static Project fromSnapshot(DocSnapshot doc, [Project modelObj]) => fromData(doc.data, modelObj)..docId = doc.id;

  static Project fromData(data, [Project modelObj]) {
    if (data == null) return null;
    return (modelObj ?? Project())
      ..projectName = data['projectName']?.toString()
      ..allowedEmailDomainsRegex = data['allowedEmailDomainsRegex']?.toString()
      ..allowedEmailDomainsMap = Map_fromData<String>(_log, 'allowedEmailDomainsMap', data)
      ..firstLanguage = data['firstLanguage']?.toString()
      ..secondLanguage = data['secondLanguage']?.toString()
      ..messageCharacterLimit = int_fromData(_log, 'messageCharacterLimit', data);
  }

  static StreamSubscription listen(DocStorage docStorage, ProjectCollectionListener listener,
          {String collectionRoot = '/$collectionName', OnErrorListener onError, @Deprecated('use onError instead') OnErrorListener onErrorListener}) =>
      listenForUpdates<Project>(_log, docStorage, listener, collectionRoot, Project.fromSnapshot, onError: onError ?? onErrorListener);

  Map<String, dynamic> toData() {
    return {
      if (projectName != null) 'projectName': projectName,
      if (allowedEmailDomainsRegex != null) 'allowedEmailDomainsRegex': allowedEmailDomainsRegex,
      if (allowedEmailDomainsMap != null) 'allowedEmailDomainsMap': allowedEmailDomainsMap,
      if (firstLanguage != null) 'firstLanguage': firstLanguage,
      if (secondLanguage != null) 'secondLanguage': secondLanguage,
      if (messageCharacterLimit != null) 'messageCharacterLimit': messageCharacterLimit,
    };
  }

  @override
  String toString() => 'Project [$docId]: ${toData().toString()}';
}

typedef ProjectCollectionListener = void Function(
  List<Project> added,
  List<Project> modified,
  List<Project> removed,
);

final _log = Logger('project.g.dart');
